const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');const bcrypt=require('bcryptjs');const {Store}=require('../src/store'),D=require('../src/domain');const {createApp}=require('../server');
async function fixture(){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'homestay-test-'));const store=new Store({mode:process.env.TEST_MONGODB_URI?'mongo':'file',uri:process.env.TEST_MONGODB_URI,file:path.join(dir,'state.json')});await store.init();const password=await bcrypt.hash('Quy@123456',10);await store.mutate(s=>{Object.assign(s,D.seedData());s.users=[{_id:D.id(),username:'admin',password,role:'admin',active:true},{_id:D.id(),username:'report',password,role:'report',active:true},{_id:D.id(),username:'reception',password,role:'reception',active:true}];});const server=createApp(store,'test-secret-at-least-48-random-bytes-for-jwt-test').listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 const call=async(url,method='GET',body,token)=>{const res=await fetch(base+url,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});const text=await res.text();let data;try{data=JSON.parse(text);}catch{data=text;}return {status:res.status,data,headers:res.headers};};
 const login=async username=>(await call('/api/auth/login','POST',{username,password:'Quy@123456'})).data.data.token;
 const body=async(overrides={})=>{const input={roomTypeId:'000000000000000000000001',checkIn:D.today(),checkOut:D.add(D.today(),2),guestCount:1,...overrides},q=(await call('/api/bookings/quote','POST',input)).data.data;return {...input,guestName:'Đào Văn Quý',phone:'0912345678',email:'quy@example.test',notes:'Yêu cầu khách',policyAccepted:true,expectedTotalAmount:q.totalAmount,expectedSettingsVersion:q.settingsSnapshot.version,requestKey:D.id()+D.id().slice(0,8)};};
 return {store,call,login,body,close:async()=>{await new Promise(r=>server.close(r));await store.close();await fs.rm(dir,{recursive:true,force:true});}};
}
async function run(fn){const f=await fixture();try{await fn(f);}finally{await f.close();}}
test('01 Tìm phòng và báo giá đủ từng đêm, phụ thu, tổng tiền',()=>run(async({call})=>{const q={roomTypeId:'000000000000000000000001',checkIn:D.today(),checkOut:D.add(D.today(),3),guestCount:2};const a=await call('/api/bookings/availability?'+new URLSearchParams(q));assert.equal(a.status,200);assert.equal(a.data.data.roomTypes[0].availableCount,5);const r=await call('/api/bookings/quote','POST',q);assert.equal(r.status,200);const b=r.data.data;assert.equal(b.nightlyPrices.length,3);assert.equal(b.extraGuestTotal,300000);assert.equal(b.totalAmount,b.roomTotal+b.extraGuestTotal);}));
test('02 Tạo booking, phát lại cùng key và chống đổi nội dung',()=>run(async({call,body,store})=>{const b=await body(),first=await call('/api/bookings/create','POST',b);assert.equal(first.status,201);assert.match(first.data.data.bookingCode,/^[A-Z0-9]{8}$/);await store.mutate(s=>{s.settings.version++;s.roomTypes[0].weekdayPrice+=100000;});const replay=await call('/api/bookings/create','POST',b);assert.equal(replay.status,201);assert.equal(replay.data.data.bookingCode,first.data.data.bookingCode);assert.equal((await store.read()).bookings.length,1);assert.equal((await call('/api/bookings/create','POST',{...b,guestName:'Khác'})).status,409);}));
test('03 Hai mươi yêu cầu tranh phòng cuối chỉ một yêu cầu thành công',()=>run(async({store,call,body})=>{await store.mutate(s=>{s.rooms.filter(r=>r.roomTypeId===s.roomTypes[0]._id).slice(1).forEach(r=>r.status='MAINTENANCE');});const b=await body();const results=await Promise.all(Array.from({length:20},(_,i)=>call('/api/bookings/create','POST',{...b,requestKey:i.toString(16).padStart(32,'0')})));assert.equal(results.filter(r=>r.status===201).length,1);assert.equal(results.filter(r=>r.status===409).length,19);assert.equal((await store.read()).bookings.length,1);}));
test('04 Sai mã/email cùng thông báo; khoá sau 10 lần sai',()=>run(async({call,body})=>{const b=await body(),created=(await call('/api/bookings/create','POST',b)).data.data;const a=await call('/api/lookup','POST',{bookingCode:created.bookingCode,email:'wrong@test.vn'}),z=await call('/api/lookup','POST',{bookingCode:'WRONG000',email:b.email});assert.equal(a.status,404);assert.equal(a.data.message,z.data.message);for(let i=2;i<10;i++)assert.equal((await call('/api/lookup','POST',{})).status,404);const blocked=await call('/api/lookup','POST',{bookingCode:created.bookingCode,email:b.email});assert.equal(blocked.status,429);assert.ok(Number(blocked.headers.get('retry-after'))>0);}));
test('05 Khách không đọc quản trị; báo cáo không xem PII và không ghi phòng',()=>run(async({call,login})=>{assert.equal((await call('/api/admin/state')).status,401);const token=await login('report'),r=await call('/api/admin/state','GET',undefined,token);assert.equal(r.status,200);assert.ok(!('bookings'in r.data.data));assert.ok(!('users'in r.data.data));assert.equal((await call('/api/admin/rooms','POST',{},token)).status,403);}));
test('06 Luồng cọc → xác nhận → nhận → trả → dọn phòng; tra cứu không lộ CCCD',()=>run(async({call,body,login,store})=>{const token=await login('admin'),b=await body(),code=(await call('/api/bookings/create','POST',b)).data.data.bookingCode,url='/api/admin/bookings/'+code;assert.equal((await call(url+'/checkin','POST',{idNumber:'123456789012'},token)).status,409);assert.equal((await call(url+'/deposit','POST',{amount:100000},token)).status,200);assert.equal((await call(url+'/confirm','POST',{},token)).status,200);assert.equal((await call(url+'/checkin','POST',{idNumber:'123456789012',internalNotes:'NỘI BỘ'},token)).status,200);const publicData=(await call('/api/lookup','POST',{bookingCode:code,email:b.email})).data.data;assert.equal(publicData.status,'CHECKED_IN');assert.equal(publicData.depositAmount,100000);assert.ok(!('idNumber'in publicData));assert.ok(!('internalNotes'in publicData));const roomId=(await store.read()).bookings[0].roomId;assert.equal((await call('/api/admin/rooms/'+roomId,'PATCH',{status:'CLEAN_VACANT'},token)).status,409);assert.equal((await call(url+'/checkout','POST',{},token)).status,200);assert.equal((await store.read()).rooms.find(r=>r._id===roomId).status,'DIRTY_VACANT');assert.equal((await call('/api/admin/rooms/'+roomId,'PATCH',{status:'CLEAN_VACANT'},token)).status,200);}));
test('07 Giá/chính sách thay đổi trả 409; không tin tổng client',()=>run(async({call,body,store})=>{const b=await body();assert.equal((await call('/api/bookings/create','POST',{...b,expectedTotalAmount:1})).data.code,'PRICE_CHANGED');await store.mutate(s=>s.settings.version++);assert.equal((await call('/api/bookings/create','POST',b)).data.code,'POLICY_CHANGED');assert.equal((await store.read()).bookings.length,0);}));
test('08 Ngày sai, quá 30 đêm, số khách sai và thiếu chấp nhận bị chặn',()=>run(async({call,body})=>{for(const bad of [{checkIn:'2026-02-30'},{checkOut:D.add(D.today(),31)},{guestCount:1.5},{guestCount:0},{guestCount:1000}]){const r=await call('/api/bookings/availability?'+new URLSearchParams({checkIn:D.today(),checkOut:D.add(D.today(),1),guestCount:1,...bad}));assert.equal(r.status,400);}const b=await body();assert.equal((await call('/api/bookings/create','POST',{...b,policyAccepted:false})).status,400);}));
test('09 Booking giữ chỗ hết hạn tự nhả phòng',()=>run(async({call,body,store})=>{const b=await body();await call('/api/bookings/create','POST',b);await store.mutate(s=>s.bookings[0].holdExpiresAt=new Date(Date.now()-1000).toISOString());const r=await call('/api/bookings/availability?'+new URLSearchParams({roomTypeId:b.roomTypeId,checkIn:b.checkIn,checkOut:b.checkOut,guestCount:1}));assert.equal(r.data.data.roomTypes[0].availableCount,5);}));
test('10 Tiện nghi đang được gán không được xoá',()=>run(async({call,login,store})=>{const token=await login('admin'),s=await store.read();assert.equal((await call('/api/admin/amenities/'+s.amenities[0]._id,'DELETE',undefined,token)).status,400);}));
test('11 Báo cáo tháng và CSV đúng tiền, có UTF-8 BOM',()=>run(async({call,login,body})=>{const token=await login('admin'),b=await body(),code=(await call('/api/bookings/create','POST',b)).data.data.bookingCode;await call('/api/admin/bookings/'+code+'/confirm','POST',{},token);const r=await call('/api/reports?month='+D.today().slice(0,7),'GET',undefined,token);assert.equal(r.data.data.totalAmount,b.expectedTotalAmount);assert.equal(r.data.data.confirmedCount,1);const csv=await call('/api/reports/export.csv?month='+D.today().slice(0,7),'GET',undefined,token);assert.equal(csv.status,200);assert.ok(csv.data.includes(code));assert.ok(csv.headers.get('content-disposition').includes('.csv'));}));
test('12 Hạn mức 5 booking/giờ; replay không tăng quota',()=>run(async({call,body})=>{const b=await body({roomTypeId:'000000000000000000000003'});for(let i=0;i<5;i++){const start=D.add(D.today(),i*3);const next=await body({roomTypeId:b.roomTypeId,checkIn:start,checkOut:D.add(start,2)});const first=await call('/api/bookings/create','POST',next);assert.equal(first.status,201);assert.equal((await call('/api/bookings/create','POST',next)).status,201);}const another=await body({roomTypeId:b.roomTypeId,checkIn:D.add(D.today(),20),checkOut:D.add(D.today(),22)});assert.equal((await call('/api/bookings/create','POST',another)).status,429);}));
test('13 Huỷ booking dùng chính sách snapshot và nhả phòng',()=>run(async({call,body,login,store})=>{const token=await login('admin'),b=await body({checkIn:D.add(D.today(),5),checkOut:D.add(D.today(),7)}),code=(await call('/api/bookings/create','POST',b)).data.data.bookingCode;await call('/api/admin/bookings/'+code+'/deposit','POST',{amount:100000},token);await store.mutate(s=>s.settings.cancellationRules=[{hoursBefore:0,refundPercent:0}]);const r=await call('/api/admin/bookings/'+code+'/cancel','POST',{},token);assert.equal(r.status,200);assert.equal(r.data.data.refundAmount,100000);assert.equal(D.availability(await store.read(),b).roomTypes[0].availableCount,5);}));
test('14 Đổi mật khẩu và bảo vệ quản trị viên đang đăng nhập',()=>run(async({call,login,store})=>{const token=await login('admin'),s=await store.read();assert.equal((await call('/api/admin/users/'+s.users[0]._id,'PATCH',{active:false,role:'admin'},token)).status,400);assert.equal((await call('/api/auth/change-password','POST',{currentPassword:'wrong',password:'New@12345'},token)).status,400);assert.equal((await call('/api/auth/change-password','POST',{currentPassword:'Quy@123456',password:'New@12345'},token)).status,200);assert.equal((await call('/api/auth/login','POST',{username:'admin',password:'Quy@123456'})).status,401);assert.equal((await call('/api/auth/login','POST',{username:'admin',password:'New@12345'})).status,200);}));
test('15 Dữ liệu file lưu và mở lại giữ nguyên booking',()=>run(async({store,call,body})=>{const b=await body(),code=(await call('/api/bookings/create','POST',b)).data.data.bookingCode;if(store.mode==='file'){const reopened=new Store({mode:'file',file:store.file});await reopened.init();assert.equal((await reopened.read()).bookings[0].bookingCode,code);await reopened.close();}else assert.equal((await store.read()).bookings[0].bookingCode,code);}));
test('16 Bộ dữ liệu mới có 50 phòng, 10 loại, 30 tiện nghi và ảnh cho mọi phòng',()=>{const s=D.seedData();assert.equal(s.rooms.length,50);assert.equal(s.roomTypes.length,10);assert.equal(s.amenities.length,30);assert.equal(new Set(s.rooms.map(r=>r.roomNumber)).size,50);for(const r of s.rooms){assert.match(r.photo,/^\/assets\/rooms\/type-\d{2}\.jpg$/);assert.ok(r.images.length>=1);assert.ok(s.roomTypes.some(t=>t._id===r.roomTypeId));}});
test('17 Cập nhật v1 không xoá booking, tài khoản, cấu hình, trạng thái; chạy lại không nhân đôi',()=>{const fresh=D.seedData();const old={...fresh,datasetVersion:undefined,amenities:fresh.amenities.slice(0,5),roomTypes:fresh.roomTypes.slice(0,3),rooms:fresh.rooms.filter(r=>Number(r.floor)<=3&&Number(r.roomNumber.slice(-2))<=4)};old.rooms[0].status='OCCUPIED';old.bookings=[{bookingCode:'TEST0001',roomId:old.rooms[0]._id}];old.users=[{username:'quy',password:'PRIVATE'}];old.settings.version=9;const oldRoomId=old.rooms[0]._id,oldAmenityId=old.amenities[0]._id;const counts=D.upgradeData(old);assert.equal(counts.addedRooms,38);assert.equal(old.rooms.length,50);assert.equal(old.rooms[0]._id,oldRoomId);assert.equal(old.rooms[0].status,'OCCUPIED');assert.equal(old.amenities[0]._id,oldAmenityId);assert.equal(old.bookings[0].bookingCode,'TEST0001');assert.equal(old.users[0].password,'PRIVATE');assert.equal(old.settings.version,9);D.upgradeData(old);assert.equal(old.rooms.length,50);assert.equal(old.amenities.length,30);});
test('18 Danh mục phòng khách có ảnh/tiện nghi và không có thông tin riêng tư',()=>run(async({call})=>{const r=await call('/api/public/rooms');assert.equal(r.status,200);assert.equal(r.data.data.length,50);for(const room of r.data.data){assert.ok(room.photo);assert.ok(room.amenities.length);assert.ok(!('status'in room));assert.ok(!('bookings'in room));}}));
test('19 Ảnh mẫu có mặt trong gói và API availability dùng ảnh mới',()=>run(async({call})=>{for(let i=1;i<=10;i++){const file=path.join(__dirname,'../public/assets/rooms/type-'+String(i).padStart(2,'0')+'.jpg');const bytes=await fs.readFile(file);assert.ok(bytes.length>10000);assert.equal(bytes[0],255);assert.equal(bytes[1],216);}const r=await call('/api/bookings/availability?'+new URLSearchParams({checkIn:D.today(),checkOut:D.add(D.today(),1),guestCount:1}));assert.equal(r.data.data.roomTypes.length,10);assert.ok(r.data.data.roomTypes.every(t=>t.photo.path.startsWith('/assets/rooms/')));}));
test('20 Sửa ảnh loại phòng cập nhật các phòng dùng ảnh chung',()=>run(async({call,login,store})=>{const token=await login('admin'),s=await store.read(),t=s.roomTypes[0],photo='/assets/rooms/type-04.jpg';const r=await call('/api/admin/room-types/'+t._id,'PUT',{...t,photo,images:[photo]},token);assert.equal(r.status,200);const after=await store.read();assert.ok(after.rooms.filter(r=>r.roomTypeId===t._id).every(r=>r.photo===photo));assert.equal((await call('/api/admin/room-types/'+t._id,'PUT',{...t,photo:'https://invalid.test/image.jpg'},token)).status,400);}));
