const API={rooms:"/api/rooms",receptionRooms:"/api/reception/rooms",roomStatus:id=>`/api/reception/rooms/${encodeURIComponent(id)}/status`,maintenance:id=>`/api/reception/rooms/${encodeURIComponent(id)}/maintenance`,bookings:"/api/reception/bookings",assignRoom:id=>`/api/reception/bookings/${encodeURIComponent(id)}/room`};
const state={rooms:[],bookings:[],bookingPage:1,totalPages:1,roomOverrides:{}};
const statusMeta={CLEAN_VACANT:{label:"Trống sạch",className:"reception-status-clean",description:"Có thể nhận/gán khách"},DIRTY_VACANT:{label:"Trống bẩn",className:"reception-status-dirty",description:"Cần dọn trước khi gán"},OCCUPIED:{label:"Đang ở",className:"reception-status-occupied",description:"Đang có khách lưu trú"},MAINTENANCE:{label:"Bảo trì",className:"reception-status-maintenance",description:"Không được gán khách"},empty_clean:{label:"Trống sạch",className:"reception-status-clean",description:"Có thể nhận/gán khách"},empty_dirty:{label:"Trống bẩn",className:"reception-status-dirty",description:"Cần dọn trước khi gán"},occupied:{label:"Đang ở",className:"reception-status-occupied",description:"Đang có khách lưu trú"},maintenance:{label:"Bảo trì",className:"reception-status-maintenance",description:"Không được gán khách"}};
const bookingMeta={PENDING:{label:"Chờ xác nhận",className:"reception-status-dirty"},CONFIRMED:{label:"Đã xác nhận",className:"reception-status-clean"},CHECKED_IN:{label:"Đang ở",className:"reception-status-occupied"},CANCELLED:{label:"Đã hủy",className:"reception-status-maintenance"}};
const $=s=>document.querySelector(s); const escapeHtml=v=>String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function notice(id,msg,type=""){const e=$("#"+id);if(!e)return;e.className=`notice ${type}`.trim();e.textContent=msg;e.hidden=false} function hide(id){const e=$("#"+id);if(e)e.hidden=true}
async function apiFetch(url,opt={}){const r=await fetch(url,{...opt,headers:{Accept:"application/json",...(opt.body?{"Content-Type":"application/json"}:{}),...(opt.headers||{})}});let p=null;try{p=await r.json()}catch{}if(!r.ok){const e=new Error(p?.message||p?.error||`Yêu cầu thất bại (${r.status})`);e.status=r.status;e.payload=p;throw e}return p}
function unwrap(payload){if(Array.isArray(payload))return payload;for(const value of [payload?.data,payload?.rooms,payload?.bookings,payload?.items,payload?.results,payload?.data?.rooms,payload?.data?.items,payload?.data?.results])if(Array.isArray(value))return value;return []}
function fmtDate(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString("vi-VN")}
function fmtMoney(v){if(v===null||v===undefined||v==="")return"—";const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("vi-VN").format(n)+" đ":String(v)}
function roomNumberOf(room){const candidates=[room?.roomNumber,room?.room_number,room?.roomCode,room?.room_code,room?.roomNo,room?.number,room?.name,room?.room?.roomNumber,room?.room?.room_number,room?.room?.roomCode,room?.room?.room_code,room?.room?.roomNo,room?.room?.number,room?.room?.name,room?.roomInfo?.roomNumber,room?.roomInfo?.room_number,room?.roomInfo?.roomCode,room?.roomInfo?.number];return candidates.find(value=>value!==null&&value!==undefined&&String(value).trim()!=="")??""}
function roomIdOf(room){return String(room?._id??room?.id??room?.roomId??room?.room_id??room?.roomID??room?.room?._id??room?.room?.id??room?.room?.roomId??room?.room?.room_id??roomNumberOf(room)??"")}
function normalizedRoomStatus(status){return({empty_clean:"CLEAN_VACANT",empty_dirty:"DIRTY_VACANT",occupied:"OCCUPIED",maintenance:"MAINTENANCE"}[String(status??"").trim().toLowerCase()]||String(status??"").trim().toUpperCase())}
function roomStatusOf(room){return state.roomOverrides[roomIdOf(room)]?.status??room?.status??room?.roomStatus??room?.room_status??room?.room?.status??room?.room?.roomStatus}
function roomMaintenanceOf(room){return{...(room?.maintenance||{}),...(state.roomOverrides[roomIdOf(room)]?.maintenance||{})}}
function renderRooms(){const filter=$("#room-status-filter").value,search=$("#room-search").value.trim().toLowerCase(),numberMatches=state.rooms.filter(room=>!search||String(roomNumberOf(room)).trim().toLowerCase().includes(search)),rooms=numberMatches.filter(room=>!filter||normalizedRoomStatus(roomStatusOf(room))===filter);const box=$("#room-list"),empty=$("#rooms-empty");box.innerHTML="";empty.hidden=rooms.length>0;if(!rooms.length){empty.textContent=search&&!numberMatches.length?"Phòng không tồn tại.":search&&numberMatches.length&&filter?"Có phòng này nhưng không thuộc trạng thái đã chọn.":"Không có phòng phù hợp.";return}empty.textContent="Không có phòng phù hợp.";rooms.forEach(r=>{const roomStatus=normalizedRoomStatus(roomStatusOf(r)),m=statusMeta[roomStatus]||statusMeta[roomStatus.toLowerCase()]||{label:roomStatus||"Không rõ",className:"",description:"Chưa xác định"};const id=r._id||r.id||r.room?._id||r.room?.id;const card=document.createElement("article");card.className="reception-room-card";const maintenance=r.maintenance||{};card.innerHTML=`<div class="reception-room-card-head"><span class="reception-room-number">Phòng ${escapeHtml(roomNumberOf(r)||"—")}</span><span class="reception-status ${m.className}">${escapeHtml(m.label)}</span></div><div class="reception-room-meta"><strong>${escapeHtml(m.description)}</strong><span>Loại phòng: ${escapeHtml(r.roomType?.name||r.roomType||r.roomTypeName||"—")}</span><span>Tầng: ${escapeHtml(r.floor??"—")}</span>${maintenance.reason?`<span>Lý do bảo trì: ${escapeHtml(maintenance.reason)}</span>`:""}${maintenance.startDate?`<span>Khoảng bảo trì: ${fmtDate(maintenance.startDate)} – ${fmtDate(maintenance.endDate)}</span>`:""}</div><div class="reception-room-actions"><button class="btn secondary reception-small-btn" data-action="clean" data-id="${escapeHtml(id)}" ${roomStatus==="DIRTY_VACANT"?"":"disabled"}>Đánh dấu sạch</button><button class="btn secondary reception-small-btn" data-action="maintenance" data-id="${escapeHtml(id)}" ${roomStatus==="OCCUPIED"||roomStatus==="MAINTENANCE"?"":"disabled"}>Bảo trì</button></div>${Array.isArray(r.statusHistory)?`<details class="reception-history"><summary>Lịch sử trạng thái</summary><div class="reception-history-list">${r.statusHistory.slice(-5).reverse().map(h=>`<div class="reception-history-item"><strong>${escapeHtml(statusMeta[normalizedRoomStatus(h.newStatus)]?.label||h.newStatus||"—")}</strong><span>${escapeHtml(statusMeta[normalizedRoomStatus(h.oldStatus)]?.label||h.oldStatus||"—")} → ${escapeHtml(h.changedBy||"—")}</span><span>${fmtDate(h.changedAt)}</span></div>`).join("")||'<div class="reception-history-item">Chưa có lịch sử.</div>'}</div></details>`:""}`;box.appendChild(card)})}
async function loadRooms(){$("#rooms-loading").hidden=false;hide("rooms-error");try{let p;try{p=await apiFetch(API.receptionRooms,{cache:"no-store"})}catch(e){if(e.status!==404)throw e;p=await apiFetch(API.rooms,{cache:"no-store"})}state.rooms=unwrap(p);populateMaintenanceRooms();renderRooms();renderMaintenanceRooms();return true}catch(e){state.rooms=[];$("#room-list").innerHTML="";$("#rooms-empty").hidden=true;$("#maintenance-room").innerHTML='<option value="">Không tải được danh sách phòng</option>';$("#maintenance-rooms-list").innerHTML="";$("#maintenance-rooms-empty").hidden=true;notice("rooms-error",e.message,"error");return false}finally{$("#rooms-loading").hidden=true}}
function populateMaintenanceRooms(){const select=$("#maintenance-room"),selected=select.value;select.innerHTML='<option value="">Chọn phòng</option>';[...state.rooms].sort((a,b)=>String(roomNumberOf(a)).localeCompare(String(roomNumberOf(b)),undefined,{numeric:true})).filter(room=>normalizedRoomStatus(roomStatusOf(room))!=="MAINTENANCE").forEach(room=>{const id=roomIdOf(room);if(!id)return;const status=normalizedRoomStatus(roomStatusOf(room)),meta=statusMeta[status]||{label:status||"Chưa rõ"};const option=document.createElement("option");option.value=id;option.textContent=`Phòng ${roomNumberOf(room)||"—"} — ${meta.label}`;select.appendChild(option)});if([...select.options].some(option=>option.value===selected))select.value=selected;if(select.options.length===1)select.options[0].textContent=state.rooms.length?"Không có phòng phù hợp để bảo trì":"Chưa tải được danh sách phòng"}
function renderMaintenanceRooms(){const list=$("#maintenance-rooms-list"),empty=$("#maintenance-rooms-empty"),rooms=state.rooms.filter(room=>normalizedRoomStatus(roomStatusOf(room))==="MAINTENANCE");list.innerHTML="";empty.hidden=rooms.length>0;if(!rooms.length)return;[...rooms].sort((a,b)=>String(roomNumberOf(a)).localeCompare(String(roomNumberOf(b)),undefined,{numeric:true})).forEach(room=>{const maintenance=roomMaintenanceOf(room),card=document.createElement("article");card.className="reception-room-card";card.innerHTML=`<div class="reception-room-card-head"><span class="reception-room-number">Phòng ${escapeHtml(roomNumberOf(room)||"—")}</span><span class="reception-status reception-status-maintenance">Đang bảo trì</span></div><div class="reception-room-meta">${maintenance.reason?`<span>Lý do: ${escapeHtml(maintenance.reason)}</span>`:""}${maintenance.startDate?`<span>Ngày bắt đầu: ${fmtDate(maintenance.startDate)}</span>`:""}${maintenance.endDate?`<span>Ngày dự kiến hoàn thành: ${fmtDate(maintenance.endDate)}</span>`:""}${room.roomType?.name||room.roomTypeName?`<span>Loại phòng: ${escapeHtml(room.roomType?.name||room.roomTypeName)}</span>`:""}</div><div class="reception-room-actions"><button class="btn primary reception-small-btn" type="button" data-action="complete-maintenance" data-id="${escapeHtml(roomIdOf(room))}">Đã hoàn thành bảo trì</button></div>`;list.appendChild(card)})}
async function completeMaintenance(roomId,button){const room=state.rooms.find(item=>roomIdOf(item)===roomId);if(!room)return notice("maintenance-message","Không tìm thấy phòng cần hoàn thành bảo trì.","error");button.disabled=true;button.textContent="Đang cập nhật...";state.roomOverrides[roomId]={status:"CLEAN_VACANT",maintenance:{}};renderRooms();renderMaintenanceRooms();populateMaintenanceRooms();populateAssignmentRooms();try{await changeStatus(roomId,"CLEAN_VACANT");notice("maintenance-message",`Đã hoàn thành bảo trì phòng ${roomNumberOf(room)}; phòng đã trở lại trạng thái trống sạch.`)}catch(error){notice("maintenance-message",`Phòng đã được cập nhật trên giao diện nhưng chưa đồng bộ được backend: ${error.message}`,"warning")}}
async function changeStatus(id,status){return apiFetch(API.roomStatus(id),{method:"PATCH",body:JSON.stringify({status})})}
async function submitMaintenance(e){e.preventDefault();hide("maintenance-message");const roomId=$("#maintenance-room").value,reason=$("#maintenance-reason").value.trim(),startDate=$("#maintenance-start").value,endDate=$("#maintenance-end").value;if(!roomId||!reason||!startDate||!endDate)return notice("maintenance-message","Vui lòng nhập đủ thông tin.","error");if(startDate>endDate)return notice("maintenance-message","Ngày bắt đầu không được lớn hơn ngày kết thúc.","error");const room=state.rooms.find(item=>roomIdOf(item)===roomId);if(!room)return notice("maintenance-message","Không tìm thấy phòng đã chọn trong danh sách phòng.","error");const b=$("#maintenance-submit");b.disabled=true;b.textContent="Đang cập nhật...";state.roomOverrides[roomId]={status:"MAINTENANCE",maintenance:{reason,startDate,endDate}};$("#maintenance-form").reset();renderRooms();renderMaintenanceRooms();populateMaintenanceRooms();populateAssignmentRooms();try{await apiFetch(API.maintenance(roomId),{method:"POST",body:JSON.stringify({reason,startDate,endDate})});notice("maintenance-message",`Đã đưa phòng ${roomNumberOf(room)} vào danh sách bảo trì.`)}catch(err){notice("maintenance-message",`Phòng đã được đánh dấu bảo trì trên giao diện nhưng chưa đồng bộ được backend: ${err.message}`,"warning")}finally{b.disabled=false;b.textContent="Đưa phòng vào bảo trì"}}
function setupRooms(){$("#room-list").addEventListener("click",async e=>{const b=e.target.closest("button[data-action]");if(!b||b.disabled)return;const id=b.dataset.id;if(b.dataset.action==="maintenance"){$("#maintenance-room").value=id;$("#maintenance-reason").focus();$("#maintenance-title").scrollIntoView({behavior:"smooth"});return}b.disabled=true;try{await changeStatus(id,"CLEAN_VACANT");await loadRooms();notice("global-message","Đã cập nhật phòng thành trống sạch.")}catch(err){notice("global-message",err.message,"error")}finally{b.disabled=false}})}
function bookingQuery(){const p=new URLSearchParams({page:String(state.bookingPage),limit:"20"});const map=[["status","#booking-status"],["checkInFrom","#booking-from"],["checkInTo","#booking-to"],["keyword","#booking-keyword"]];map.forEach(([k,s])=>{const v=$(s).value.trim();if(v)p.set(k,v)});return p.toString()}
function renderBookings(rows,p){const body=$("#booking-table-body");body.innerHTML="";$("#bookings-empty").hidden=rows.length>0;rows.forEach(r=>{const m=bookingMeta[r.status]||{label:r.status||"—",className:""},tr=document.createElement("tr");tr.innerHTML=`<td>${escapeHtml(r.bookingCode||r.code||r._id||"—")}</td><td>${escapeHtml(r.guestName||r.customerName||r.guest?.name||"—")}<br><small>${escapeHtml(r.phone||r.guestPhone||r.guest?.phone||"")}</small></td><td>${escapeHtml(r.roomTypeName||r.roomType?.name||r.roomType||"—")}</td><td>${fmtDate(r.checkIn||r.checkinDate)}</td><td>${fmtDate(r.checkOut||r.checkoutDate)}</td><td>${fmtMoney(r.totalAmount??r.totalPrice??r.total)}</td><td><span class="reception-status ${m.className}">${escapeHtml(m.label)}</span></td>`;body.appendChild(tr)});state.totalPages=Number(p?.totalPages||p?.pagination?.totalPages||Math.max(1,Math.ceil(Number(p?.total||rows.length)/20)));$("#booking-page-label").textContent=`Trang ${state.bookingPage} / ${state.totalPages}`;$("#booking-prev").disabled=state.bookingPage<=1;$("#booking-next").disabled=state.bookingPage>=state.totalPages}
async function loadBookings(){hide("bookings-error");$("#bookings-loading").hidden=false;try{const p=await apiFetch(`${API.bookings}?${bookingQuery()}`);renderBookings(unwrap(p),p)}catch(e){$("#booking-table-body").innerHTML="";notice("bookings-error",e.status===404?"Backend hiện chưa có API GET /api/reception/bookings; frontend không dùng dữ liệu giả.":e.message,"error")}finally{$("#bookings-loading").hidden=true}}
function bind(){$("#room-search").addEventListener("input",renderRooms);$("#room-status-filter").addEventListener("change",renderRooms);$("#reload-rooms").addEventListener("click",async()=>{const button=$("#reload-rooms"),label=button.textContent;button.disabled=true;button.textContent="Đang làm mới...";try{await loadRooms()}finally{button.disabled=false;button.textContent=label}});$("#maintenance-form").addEventListener("submit",submitMaintenance);$("#maintenance-rooms-list").addEventListener("click",event=>{const button=event.target.closest('button[data-action="complete-maintenance"]');if(button&&!button.disabled)completeMaintenance(button.dataset.id,button)});$("#maintenance-clear").addEventListener("click",()=>{$("#maintenance-form").reset();hide("maintenance-message")});["#booking-status","#booking-from","#booking-to"].forEach(s=>$(s).addEventListener("change",()=>{state.bookingPage=1;loadBookings()}));$("#booking-keyword").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();state.bookingPage=1;loadBookings()}});$("#reload-bookings").addEventListener("click",loadBookings);$("#booking-prev").addEventListener("click",()=>{if(state.bookingPage>1){state.bookingPage--;loadBookings()}});$("#booking-next").addEventListener("click",()=>{if(state.bookingPage<state.totalPages){state.bookingPage++;loadBookings()}});setupRooms()}
document.addEventListener("DOMContentLoaded",()=>{bind();loadRooms();loadBookings()});

state.assignments=[];
const originalRenderBookings=renderBookings;
renderBookings=function(rows,p){originalRenderBookings(rows,p);state.bookings=rows;populateAssignmentBookings()};
const originalLoadRooms=loadRooms;
loadRooms=async function(){const loaded=await originalLoadRooms();populateAssignmentRooms();return loaded};
const originalLoadBookings=loadBookings;
loadBookings=async function(){await originalLoadBookings();if(!$("#bookings-error").hidden){state.bookings=[];populateAssignmentBookings()}};
const recordId=record=>String(record?._id??record?.id??"");
const isCleanRoom=room=>normalizedRoomStatus(roomStatusOf(room))==="CLEAN_VACANT";
function populateAssignmentBookings(){const select=$("#assign-booking"),selected=select.value,assigned=new Set(state.assignments.map(item=>item.bookingId));select.innerHTML='<option value="">Chọn booking</option>';state.bookings.filter(booking=>recordId(booking)&&!assigned.has(recordId(booking))).forEach(booking=>{const option=document.createElement("option");option.value=recordId(booking);option.textContent=`${booking.bookingCode||booking.code||recordId(booking)} — ${booking.guestName||booking.customerName||booking.guest?.name||"Khách chưa rõ"}`;select.appendChild(option)});if([...select.options].some(option=>option.value===selected))select.value=selected;else select.value="";if(select.options.length===1)select.options[0].textContent="Không có booking khả dụng trên trang này";updateAssignmentButton()}
function populateAssignmentRooms(){const select=$("#assign-room"),selected=select.value,assigned=new Set(state.assignments.map(item=>item.roomId));select.innerHTML='<option value="">Chọn phòng trống sạch</option>';state.rooms.filter(room=>recordId(room)&&isCleanRoom(room)&&!assigned.has(recordId(room))).forEach(room=>{const option=document.createElement("option");option.value=recordId(room);option.textContent=`Phòng ${room.roomNumber??room.roomCode??"—"} — ${room.roomType?.name||room.roomTypeName||room.roomType||"Trống sạch"}`;select.appendChild(option)});if([...select.options].some(option=>option.value===selected))select.value=selected;else select.value="";if(select.options.length===1)select.options[0].textContent="Không có phòng trống sạch khả dụng";updateAssignmentButton()}
function updateAssignmentButton(){$("#assign-submit").disabled=!$("#assign-booking").value||!$("#assign-room").value}
function renderAssignments(){const box=$("#assignment-results");box.innerHTML="";if(!state.assignments.length)return;const heading=document.createElement("h3");heading.textContent="Kết quả mô phỏng";box.appendChild(heading);state.assignments.forEach(item=>{const row=document.createElement("div");row.className="reception-assignment-item";row.innerHTML=`<strong>${escapeHtml(item.bookingLabel)}</strong><span>→</span><span>${escapeHtml(item.roomLabel)}</span><span class="reception-status reception-status-clean">Đã gán (mô phỏng)</span>`;box.appendChild(row)})}
function assignRoomPreview(){const booking=state.bookings.find(item=>recordId(item)===$("#assign-booking").value),room=state.rooms.find(item=>recordId(item)===$("#assign-room").value);if(!booking||!room||!isCleanRoom(room))return;state.assignments.push({bookingId:recordId(booking),roomId:recordId(room),bookingLabel:`${booking.bookingCode||booking.code||recordId(booking)} — ${booking.guestName||booking.customerName||booking.guest?.name||"Khách chưa rõ"}`,roomLabel:`Phòng ${room.roomNumber??room.roomCode??"—"}`});renderAssignments();populateAssignmentBookings();populateAssignmentRooms();notice("assign-message","Đã gán phòng trong bản xem trước. Thao tác này chưa được lưu vào backend.","warning")}
document.addEventListener("DOMContentLoaded",()=>{$("#assign-booking").addEventListener("change",updateAssignmentButton);$("#assign-room").addEventListener("change",updateAssignmentButton);$("#assign-submit").addEventListener("click",assignRoomPreview);renderAssignments()});
