require('dotenv').config();
const express=require('express'),path=require('node:path'),crypto=require('node:crypto'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken');
const {Store}=require('./src/store');const D=require('./src/domain');
function createApp(store,secret){
 const app=express();app.disable('x-powered-by');app.use(express.json({limit:'64kb'}));
 app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','DENY');if(req.path.startsWith('/api/'))res.setHeader('Cache-Control','no-store');next();});
 const route=fn=>(req,res,next)=>Promise.resolve(fn(req,res)).catch(next);const ok=(res,data,status=200)=>res.status(status).json({success:true,data});
 // Middleware with explicit next: verify current account and role on every request.
 const requireRole=(roles=['admin','reception','report'])=>(req,res,next)=>{(async()=>{let token;try{token=jwt.verify(String(req.headers.authorization||'').replace(/^Bearer /,''),secret);}catch{throw new D.AppError(401,'UNAUTHORIZED','Vui lòng đăng nhập lại.');}const s=await store.read(),u=s.users.find(u=>u._id===token.sub&&u.active);if(!u)throw new D.AppError(401,'UNAUTHORIZED','Vui lòng đăng nhập lại.');if(!roles.includes(u.role))throw new D.AppError(403,'FORBIDDEN','Tài khoản không có quyền thực hiện thao tác.');req.user=u;next();})().catch(next);};
 const loginAttempts=new Map();
 app.get('/api/health',(req,res)=>ok(res,{name:'HOMESTAY',dataMode:store.mode}));
 app.get('/api/public/rooms',route(async(req,res)=>{const s=await store.read();ok(res,s.rooms.filter(r=>s.roomTypes.some(t=>t._id===r.roomTypeId&&t.active)).map(r=>{const t=s.roomTypes.find(t=>t._id===r.roomTypeId);return {_id:r._id,roomNumber:r.roomNumber,floor:r.floor,roomTypeId:t._id,roomTypeName:t.name,description:t.description,area:t.area,standardCapacity:t.standardCapacity,maxCapacity:t.maxCapacity,weekdayPrice:t.weekdayPrice,weekendPrice:t.weekendPrice,photo:r.photo||t.photo,images:r.images||t.images||[],amenities:s.amenities.filter(a=>a.active&&t.amenityIds.includes(a._id)).map(a=>({name:a.name,icon:a.icon}))};}));}));
 app.get('/api/public/settings',route(async(req,res)=>ok(res,(await store.read()).settings)));
 app.get('/api/public/room-types',route(async(req,res)=>{const s=await store.read();ok(res,s.roomTypes.filter(t=>t.active).map(t=>({...t,amenities:s.amenities.filter(a=>a.active&&t.amenityIds.includes(a._id))})));}));
 app.get('/api/bookings/availability',route(async(req,res)=>ok(res,D.availability(await store.read(),req.query))));
 app.post('/api/bookings/quote',route(async(req,res)=>{const s=await store.read(),q=D.quote(s,req.body);if(!D.availability(s,req.body).roomTypes.length)D.fail('Không còn phòng.','NO_AVAILABILITY',409);ok(res,q);}));
 app.post('/api/bookings/create',route(async(req,res)=>ok(res,await store.mutate(s=>D.createBooking(s,req.body,req.ip)),201)));
 const lookup=route(async(req,res)=>{const result=await store.mutate(s=>D.lookup(s,req.method==='GET'?req.query:req.body,req.ip));if(result.error)throw result.error;ok(res,result.data);});
 app.get('/api/bookings/lookup',lookup);app.post('/api/lookup',lookup);
 app.post('/api/auth/login',route(async(req,res)=>{const key=req.ip,now=Date.now();let a=loginAttempts.get(key);if(!a||a.until<now)a={count:0,until:now+900000};if(a.count>=10)throw new D.AppError(429,'RATE_LIMITED','Thử lại sau 15 phút.',Math.ceil((a.until-now)/1000));const s=await store.read(),u=s.users.find(u=>u.username===req.body.username&&u.active);const valid=typeof req.body.password==='string'&&u&&await bcrypt.compare(req.body.password,u.password);if(!valid){a.count++;loginAttempts.set(key,a);throw new D.AppError(401,'INVALID_LOGIN','Tài khoản hoặc mật khẩu không chính xác.');}loginAttempts.delete(key);ok(res,{token:jwt.sign({sub:u._id},secret,{expiresIn:'30m'}),user:{username:u.username,role:u.role}});}));
 app.get('/api/auth/me',requireRole(),(req,res)=>ok(res,{username:req.user.username,role:req.user.role}));
 app.post('/api/auth/change-password',requireRole(),route(async(req,res)=>{const {currentPassword,password}=req.body;if(typeof currentPassword!=='string'||!await bcrypt.compare(currentPassword,req.user.password))D.fail('Mật khẩu hiện tại không đúng.');if(typeof password!=='string'||password.length<8||password.length>72)D.fail('Mật khẩu mới cần 8–72 ký tự.');const hash=await bcrypt.hash(password,10);await store.mutate(s=>{s.users.find(u=>u._id===req.user._id).password=hash;D.log(s,req.user.username,'CHANGE_PASSWORD','Đổi mật khẩu');});ok(res,{});}));
 app.get('/api/admin/state',requireRole(),route(async(req,res)=>{const s=await store.read();D.expire(s);const result={rooms:s.rooms,roomTypes:s.roomTypes,amenities:s.amenities,settings:s.settings};if(['admin','reception'].includes(req.user.role))result.bookings=s.bookings.map(b=>{const {fingerprint,requestKey,ip,...data}=b;return data;});if(req.user.role==='admin'){result.users=s.users.map(({password,...u})=>u);result.audit=s.audit;}ok(res,result);}));
 app.post('/api/admin/bookings/:code/:action',requireRole(['admin','reception']),route(async(req,res)=>ok(res,await store.mutate(s=>D.transition(s,req.params.code,req.params.action,req.body,req.user.username)))));
 app.patch('/api/admin/rooms/:id',requireRole(['admin','reception']),route(async(req,res)=>{const status=req.body.status;if(!['CLEAN_VACANT','DIRTY_VACANT','MAINTENANCE'].includes(status))D.fail('Trạng thái phòng không hợp lệ.');ok(res,await store.mutate(s=>{D.expire(s);const r=s.rooms.find(r=>r._id===req.params.id);if(!r)D.fail('Không tìm thấy phòng.','NOT_FOUND',404);if(r.status==='OCCUPIED')D.fail('Phải trả phòng trước khi đổi trạng thái.','STATE_CONFLICT',409);if(status==='MAINTENANCE'&&s.bookings.some(b=>b.roomId===r._id&&['PENDING','CONFIRMED','CHECKED_IN'].includes(b.status)))D.fail('Phòng đang được giữ hoặc đặt.','STATE_CONFLICT',409);r.status=status;D.log(s,req.user.username,'ROOM_STATUS',r.roomNumber+': '+status);return r;}));}));
 app.post('/api/admin/rooms',requireRole(['admin']),route(async(req,res)=>ok(res,await store.mutate(s=>{const {roomNumber,roomTypeId}=req.body,floor=Number(req.body.floor);if(typeof roomNumber!=='string'||!roomNumber.trim()||roomNumber.length>20||!Number.isInteger(floor)||floor<1||!s.roomTypes.some(t=>t._id===roomTypeId))D.fail('Thông tin phòng không hợp lệ.');if(s.rooms.some(r=>r.roomNumber===roomNumber.trim()))D.fail('Số phòng đã tồn tại.','DUPLICATE',409);const r={_id:D.id(),roomNumber:roomNumber.trim(),roomTypeId,floor,status:'CLEAN_VACANT'};s.rooms.push(r);D.log(s,req.user.username,'CREATE_ROOM',r.roomNumber);return r;}),201)));
 app.delete('/api/admin/rooms/:id',requireRole(['admin']),route(async(req,res)=>{await store.mutate(s=>{if(s.bookings.some(b=>b.roomId===req.params.id))D.fail('Không xoá phòng đã có booking.');s.rooms=s.rooms.filter(r=>r._id!==req.params.id);D.log(s,req.user.username,'DELETE_ROOM',req.params.id);});ok(res,{});}));
 const typeBody=(b,s)=>{const existing=s.roomTypes.find(t=>t._id===b._id);const photo=b.photo??existing?.photo??'/assets/rooms/type-01.jpg';if(typeof photo!=='string'||!/^\/assets\/[a-zA-Z0-9/_-]+\.(jpg|jpeg|png|webp)$/.test(photo))D.fail('Ảnh cần là đường dẫn trong /assets/.');const images=b.images??existing?.images??[photo];if(!Array.isArray(images)||images.length>10||images.some(p=>typeof p!=='string'||!/^\/assets\/[a-zA-Z0-9/_-]+\.(jpg|jpeg|png|webp)$/.test(p)))D.fail('Danh sách ảnh không hợp lệ.');const t={name:String(b.name||'').trim(),description:String(b.description||'').slice(0,2000),standardCapacity:Number(b.standardCapacity),maxCapacity:Number(b.maxCapacity),weekdayPrice:Number(b.weekdayPrice),weekendPrice:Number(b.weekendPrice),amenityIds:Array.isArray(b.amenityIds)?[...new Set(b.amenityIds)]:[],active:b.active!==false,photo,images:[photo,...images].filter((x,i,a)=>a.indexOf(x)===i)};if(!t.name||t.name.length>100||!Number.isSafeInteger(t.standardCapacity)||t.standardCapacity<1||!Number.isSafeInteger(t.maxCapacity)||t.maxCapacity<t.standardCapacity||t.maxCapacity>100||!D.money(t.weekdayPrice)||!D.money(t.weekendPrice)||t.weekdayPrice<1||t.weekendPrice<1||t.amenityIds.some(id=>!s.amenities.some(a=>a._id===id)))D.fail('Thông tin loại phòng không hợp lệ.');return t;};
 app.post('/api/admin/room-types',requireRole(['admin']),route(async(req,res)=>ok(res,await store.mutate(s=>{const t={_id:D.id(),...typeBody(req.body,s)};s.roomTypes.push(t);D.log(s,req.user.username,'CREATE_TYPE',t.name);return t;}),201)));
 app.put('/api/admin/room-types/:id',requireRole(['admin']),route(async(req,res)=>ok(res,await store.mutate(s=>{const t=s.roomTypes.find(t=>t._id===req.params.id);if(!t)D.fail('Không tìm thấy loại phòng.','NOT_FOUND',404);const previousPhoto=t.photo,previousImages=JSON.stringify(t.images);Object.assign(t,typeBody({...req.body,_id:t._id},s));for(const r of s.rooms.filter(r=>r.roomTypeId===t._id)){if(!r.photo||r.photo===previousPhoto)r.photo=t.photo;if(!r.images||JSON.stringify(r.images)===previousImages)r.images=t.images;}D.log(s,req.user.username,'UPDATE_TYPE',t.name);return t;}))));
 app.delete('/api/admin/room-types/:id',requireRole(['admin']),route(async(req,res)=>{await store.mutate(s=>{if(s.rooms.some(r=>r.roomTypeId===req.params.id)||s.bookings.some(b=>b.roomTypeId===req.params.id))D.fail('Loại phòng đã được sử dụng; hãy vô hiệu hoá.');s.roomTypes=s.roomTypes.filter(t=>t._id!==req.params.id);});ok(res,{});}));
 app.post('/api/admin/amenities',requireRole(['admin']),route(async(req,res)=>ok(res,await store.mutate(s=>{const name=String(req.body.name||'').trim();if(!name||name.length>100)D.fail('Tên tiện nghi không hợp lệ.');if(s.amenities.some(a=>a.name.toLowerCase()===name.toLowerCase()))D.fail('Tiện nghi đã tồn tại.');const a={_id:D.id(),name,icon:String(req.body.icon||'✓').slice(0,8),active:true};s.amenities.push(a);D.log(s,req.user.username,'CREATE_AMENITY',name);return a;}),201)));
 app.put('/api/admin/amenities/:id',requireRole(['admin']),route(async(req,res)=>ok(res,await store.mutate(s=>{const a=s.amenities.find(a=>a._id===req.params.id);if(!a)D.fail('Không tìm thấy tiện nghi.','NOT_FOUND',404);const name=String(req.body.name||'').trim();if(!name||name.length>100||s.amenities.some(x=>x._id!==a._id&&x.name.toLowerCase()===name.toLowerCase()))D.fail('Tên tiện nghi trống hoặc trùng.');Object.assign(a,{name,icon:String(req.body.icon||'✓').slice(0,8),active:req.body.active!==false});D.log(s,req.user.username,'UPDATE_AMENITY',name);return a;}))));
 app.delete('/api/admin/amenities/:id',requireRole(['admin']),route(async(req,res)=>{await store.mutate(s=>{if(s.roomTypes.some(t=>t.amenityIds.includes(req.params.id)))D.fail('Tiện nghi đang gán cho loại phòng; hãy gỡ gán hoặc vô hiệu hoá.');s.amenities=s.amenities.filter(a=>a._id!==req.params.id);});ok(res,{});}));
 app.put('/api/admin/settings',requireRole(['admin']),route(async(req,res)=>{const b=req.body;if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(b.checkInTime)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(b.checkOutTime)||!D.money(Number(b.extraGuestPerNight))||!Array.isArray(b.cancellationRules)||b.cancellationRules.length<1||b.cancellationRules.length>3||b.cancellationRules.some((r,i)=>!Number.isSafeInteger(r.hoursBefore)||r.hoursBefore<0||!Number.isFinite(r.refundPercent)||r.refundPercent<0||r.refundPercent>100||(i&&b.cancellationRules[i-1].hoursBefore<=r.hoursBefore)))D.fail('Giờ, phụ thu hoặc chính sách huỷ không hợp lệ.');ok(res,await store.mutate(s=>{s.settings={version:s.settings.version+1,checkInTime:b.checkInTime,checkOutTime:b.checkOutTime,extraGuestPerNight:Number(b.extraGuestPerNight),cancellationRules:b.cancellationRules};D.log(s,req.user.username,'UPDATE_SETTINGS','v'+s.settings.version);return s.settings;}));}));
 app.get('/api/admin/users',requireRole(['admin']),route(async(req,res)=>ok(res,(await store.read()).users.map(({password,...u})=>u))));
 app.post('/api/admin/users',requireRole(['admin']),route(async(req,res)=>{const b=req.body;if(!/^[a-zA-Z0-9_]{3,30}$/.test(b.username)||typeof b.password!=='string'||b.password.length<8||b.password.length>72||!['admin','reception','report'].includes(b.role))D.fail('Tài khoản, mật khẩu hoặc vai trò không hợp lệ.');const password=await bcrypt.hash(b.password,10);ok(res,await store.mutate(s=>{if(s.users.some(u=>u.username===b.username))D.fail('Tài khoản đã tồn tại.');const u={_id:D.id(),username:b.username,email:String(b.email||''),role:b.role,password,active:true};s.users.push(u);D.log(s,req.user.username,'CREATE_USER',u.username);const {password:ignored,...safe}=u;return safe;}),201);}));
 app.patch('/api/admin/users/:id',requireRole(['admin']),route(async(req,res)=>{const b=req.body;if(!['admin','reception','report'].includes(b.role)||typeof b.active!=='boolean')D.fail('Vai trò hoặc trạng thái không hợp lệ.');ok(res,await store.mutate(s=>{const u=s.users.find(u=>u._id===req.params.id);if(!u)D.fail('Không tìm thấy tài khoản.');if(u._id===req.user._id&&(!b.active||b.role!=='admin'))D.fail('Không thể tự khoá hoặc hạ quyền tài khoản đang dùng.');if(u.role==='admin'&&u.active&&(!b.active||b.role!=='admin')&&s.users.filter(x=>x.role==='admin'&&x.active).length<=1)D.fail('Phải giữ ít nhất một quản trị viên.');Object.assign(u,{role:b.role,active:b.active});D.log(s,req.user.username,'UPDATE_USER',u.username);const {password,...safe}=u;return safe;}));}));
 app.post('/api/admin/users/:id/reset-password',requireRole(['admin']),route(async(req,res)=>{const p=req.body.password;if(typeof p!=='string'||p.length<8||p.length>72)D.fail('Mật khẩu cần 8–72 ký tự.');const hash=await bcrypt.hash(p,10);await store.mutate(s=>{const u=s.users.find(u=>u._id===req.params.id);if(!u)D.fail('Không tìm thấy tài khoản.');u.password=hash;D.log(s,req.user.username,'RESET_PASSWORD',u.username);});ok(res,{});}));
 app.get('/api/reports',requireRole(['admin','report']),route(async(req,res)=>{const r=D.report(await store.read(),req.query.month||D.today().slice(0,7));const {bookings,...safe}=r;ok(res,safe);}));
 app.get('/api/reports/export.csv',requireRole(['admin','report']),route(async(req,res)=>{const r=D.report(await store.read(),req.query.month||D.today().slice(0,7));const cell=x=>'"'+String(x??'').replace(/^[=+@-]/,"'").replaceAll('"','""')+'"';const rows=[['Mã booking','Loại phòng','Nhận phòng','Trả phòng','Số đêm','Tổng tiền','Tiền cọc','Trạng thái'],...r.bookings.map(b=>[b.bookingCode,b.roomTypeName,b.checkIn,b.checkOut,b.numberOfNights,b.totalAmount,b.depositAmount,D.statusLabels[b.status]])];res.type('text/csv; charset=utf-8').attachment(`HOMESTAY_${r.month}.csv`).send('\uFEFF'+rows.map(row=>row.map(cell).join(',')).join('\r\n'));}));
 app.use(express.static(path.join(__dirname,'public')));app.use((req,res)=>res.status(404).json({success:false,code:'NOT_FOUND',message:'Không tìm thấy trang hoặc API.'}));
 app.use((err,req,res,next)=>{const status=err.status||500;if(status>=500)console.error(err.message);if(err.retryAfter)res.set('Retry-After',String(err.retryAfter));res.status(status).json({success:false,code:err.code||'SERVER_ERROR',message:status>=500?'Lỗi máy chủ. Vui lòng thử lại.':err.message});});return app;
}
async function main(){const mode=process.env.DATA_MODE||'mongo';if(!['mongo','file'].includes(mode))throw new Error('DATA_MODE phải là mongo hoặc file.');const store=new Store({mode,uri:process.env.MONGODB_URI||'mongodb://127.0.0.1:27017/HOMESTAY_QUY_TEST',file:path.join(__dirname,'data/homestay.json')});await store.init();const secret=process.env.JWT_SECRET;if(!secret||secret==='replace-with-a-long-random-secret')throw new Error('Hãy chạy bash scripts/setup.sh để tạo JWT_SECRET riêng.');const server=createApp(store,secret).listen(Number(process.env.PORT||3001),'127.0.0.1',()=>console.log(`HOMESTAY: http://localhost:${process.env.PORT||3001} — ${mode}`));const stop=()=>server.close(()=>store.close().then(()=>process.exit()));process.on('SIGINT',stop);process.on('SIGTERM',stop);}
if(require.main===module)main().catch(e=>{console.error('Không khởi động được:',e.message);console.error('Kiểm tra MongoDB hoặc dùng npm run setup:demo.');process.exitCode=1;});module.exports={createApp};
