const crypto = require('node:crypto');
class AppError extends Error { constructor(status,code,message,retryAfter=0){super(message); Object.assign(this,{status,code,retryAfter});} }
const fail=(message,code='VALIDATION_ERROR',status=400)=>{throw new AppError(status,code,message)};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const day=(s)=> typeof s==='string' && /^\d{4}-\d{2}-\d{2}$/.test(s) && Number.isFinite(Date.parse(s)) && new Date(s).toISOString().slice(0,10)===s;
const add=(d,n)=>new Date(Date.parse(d)+n*86400000).toISOString().slice(0,10);
const money=n=>Number.isSafeInteger(n)&&n>=0;
const id=()=>crypto.randomBytes(12).toString('hex');
const statusLabels={PENDING:'Chờ xác nhận',CONFIRMED:'Đã xác nhận',CHECKED_IN:'Đang ở',COMPLETED:'Đã trả phòng',CANCELLED:'Đã huỷ',EXPIRED:'Hết hạn giữ chỗ'};
const {amenityCatalog,typeCatalog}=require('./catalog');
function upgradeData(s){
 if(s.datasetVersion>=2)return {addedRooms:0,addedTypes:0,addedAmenities:0};
 const counts={addedRooms:0,addedTypes:0,addedAmenities:0};
 s.amenities ||= [];s.roomTypes ||= [];s.rooms ||= [];
 const amenityIds=amenityCatalog.map(([name,icon])=>{let a=s.amenities.find(x=>x.name.toLocaleLowerCase('vi')===name.toLocaleLowerCase('vi'));if(!a){a={_id:id(),name,icon,active:true};s.amenities.push(a);counts.addedAmenities++;}else if(['⌁','❄','☀','P'].includes(a.icon))a.icon=icon;return a._id;});
 typeCatalog.forEach(([name,standardCapacity,maxCapacity,weekdayPrice,weekendPrice,area,description,indexes],i)=>{
  const typeId=(i+1).toString(16).padStart(24,'0'), photo=`/assets/rooms/type-${String(i+1).padStart(2,'0')}.jpg`;
  let t=s.roomTypes.find(x=>x._id===typeId);
  const images=[photo,`/assets/rooms/type-${String((i+3)%10+1).padStart(2,'0')}.jpg`,`/assets/rooms/type-${String((i+6)%10+1).padStart(2,'0')}.jpg`];
  if(!t){t={_id:typeId,name,standardCapacity,maxCapacity,weekdayPrice,weekendPrice,area,description,amenityIds:indexes.map(n=>amenityIds[n]),active:true,photo,images};s.roomTypes.push(t);counts.addedTypes++;}
  else {if(!t.photo||t.photo.includes('placeholder'))t.photo=photo;if(!t.images?.length)t.images=images;if(!t.area)t.area=area;if(t.description==='Không gian ấm cúng, sạch sẽ, phù hợp cho kỳ nghỉ của bạn.')t.description=description;}
  for(let j=1;j<=5;j++){const roomNumber=`${i+1}${String(j).padStart(2,'0')}`;let r=s.rooms.find(x=>x.roomNumber===roomNumber);if(!r){r={_id:id(),roomNumber,floor:i+1,roomTypeId:typeId,status:'CLEAN_VACANT'};s.rooms.push(r);counts.addedRooms++;}if(!r.photo)r.photo=t.photo;if(!r.images?.length)r.images=t.images;}
 });
 s.datasetVersion=2;return counts;
}
function seedData(){
 const s={users:[],amenities:[],roomTypes:[],rooms:[],bookings:[],audit:[],lookupFailures:{},settings:{version:1,checkInTime:'14:00',checkOutTime:'12:00',extraGuestPerNight:100000,cancellationRules:[{hoursBefore:48,refundPercent:100},{hoursBefore:24,refundPercent:50},{hoursBefore:0,refundPercent:0}]}};
 upgradeData(s);return s;
}
function criteria(b){if(!day(b.checkIn)||b.checkIn<today()||!day(b.checkOut)) fail('Chọn ngày nhận từ hôm nay và ngày trả hợp lệ.');const n=(Date.parse(b.checkOut)-Date.parse(b.checkIn))/86400000;if(n<1||n>30)fail('Kỳ lưu trú phải từ 1 đến 30 đêm.');const guests=Number(b.guestCount);if(!Number.isSafeInteger(guests)||guests<1||guests>100)fail('Số khách không hợp lệ.'); if(b.roomTypeId && !/^[a-f0-9]{24}$/i.test(b.roomTypeId))fail('Loại phòng không hợp lệ.');return {...b,guestCount:guests,numberOfNights:n};}
function expire(s){const now=Date.now();for(const b of s.bookings)if(b.status==='PENDING'&&Date.parse(b.holdExpiresAt)<=now)b.status='EXPIRED';}
function freeRooms(s,c){expire(s);return s.rooms.filter(r=>r.roomTypeId===c.roomTypeId&&r.status!=='MAINTENANCE'&&!s.bookings.some(b=>b.roomId===r._id&&['PENDING','CONFIRMED','CHECKED_IN'].includes(b.status)&&b.checkIn<c.checkOut&&b.checkOut>c.checkIn));}
function quote(s,body){const c=criteria(body),t=s.roomTypes.find(t=>t._id===c.roomTypeId&&t.active);if(!t||t.maxCapacity<c.guestCount)fail('Loại phòng không phù hợp.');const nightlyPrices=Array.from({length:c.numberOfNights},(_,i)=>{const night=add(c.checkIn,i),weekend=[5,6].includes(new Date(night).getUTCDay()),basePrice=weekend?t.weekendPrice:t.weekdayPrice,extraGuestCount=Math.max(0,c.guestCount-t.standardCapacity),extraGuestUnitPrice=s.settings.extraGuestPerNight,surchargeAmount=extraGuestCount*extraGuestUnitPrice;return {night,basePrice,extraGuestCount,extraGuestUnitPrice,surchargeAmount,lineTotal:basePrice+surchargeAmount,priceKind:weekend?'WEEKEND':'WEEKDAY',label:weekend?'Cuối tuần':'Ngày thường'};});const roomTotal=nightlyPrices.reduce((a,r)=>a+r.basePrice,0),extraGuestTotal=nightlyPrices.reduce((a,r)=>a+r.surchargeAmount,0);if(!money(roomTotal)||!money(extraGuestTotal)||!money(roomTotal+extraGuestTotal))fail('Giá hoặc phụ thu vượt giới hạn hợp lệ.');return {roomTypeId:t._id,roomTypeName:t.name,checkIn:c.checkIn,checkOut:c.checkOut,guestCount:c.guestCount,numberOfNights:c.numberOfNights,nightlyPrices,roomTotal,extraGuestTotal,totalAmount:roomTotal+extraGuestTotal,settingsSnapshot:structuredClone(s.settings)};}
function availability(s,body){const c=criteria(body);return {roomTypes:s.roomTypes.filter(t=>t.active&&t.maxCapacity>=c.guestCount&&(!c.roomTypeId||c.roomTypeId===t._id)).map(t=>{const availableCount=freeRooms(s,{...c,roomTypeId:t._id}).length;return {roomTypeId:t._id,name:t.name,standardCapacity:t.standardCapacity,maxCapacity:t.maxCapacity,availableCount,fromPrice:Math.min(t.weekdayPrice,t.weekendPrice),images:t.images||[],photo:{path:t.photo||'/modules/bookings/assets/room-placeholder.svg',alt:'Ảnh mẫu '+t.name},amenities:s.amenities.filter(a=>a.active&&t.amenityIds.includes(a._id)).map(a=>({name:a.name,icon:a.icon})),area:t.area};}).filter(t=>t.availableCount>0)};}
const bookingResult=b=>({bookingCode:b.bookingCode,roomTypeName:b.roomTypeName,checkInDay:b.checkIn,checkOutDay:b.checkOut,numberOfNights:b.numberOfNights,totalAmount:b.totalAmount,status:'PENDING',holdExpiresAt:b.holdExpiresAt});
function log(s,actor,action,detail){s.audit.unshift({_id:id(),at:new Date().toISOString(),actor,action,detail});s.audit=s.audit.slice(0,2000);}
function createBooking(s,body,ip){
 const fields=['roomTypeId','checkIn','checkOut','guestCount','guestName','phone','email','notes','policyAccepted','expectedTotalAmount','expectedSettingsVersion','requestKey'];const b=Object.fromEntries(fields.map(k=>[k,body[k]??(k==='notes'?'':null)]));
 if(typeof b.requestKey!=='string'||!/^[a-f0-9]{32}$/i.test(b.requestKey))fail('Mã yêu cầu không hợp lệ.');
 if(typeof b.guestName!=='string'||!b.guestName.trim()||b.guestName.length>255||typeof b.phone!=='string'||!/^0[35789]\d{8}$/.test(b.phone)||typeof b.email!=='string'||b.email.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(b.email)||typeof b.notes!=='string'||b.notes.length>2000||b.policyAccepted!==true||!money(b.expectedTotalAmount)||!Number.isInteger(b.expectedSettingsVersion))fail('Kiểm tra họ tên, điện thoại, email và đồng ý chính sách.');
 b.email=b.email.trim().toLowerCase();b.guestName=b.guestName.trim();const fingerprint=crypto.createHash('sha256').update(JSON.stringify(b)).digest('hex');const old=s.bookings.find(x=>x.requestKey===b.requestKey);if(old){if(old.fingerprint!==fingerprint)fail('Mã yêu cầu đã được dùng với nội dung khác.','REQUEST_CONFLICT',409);return bookingResult(old);}
 const q=quote(s,b);if(q.settingsSnapshot.version!==b.expectedSettingsVersion)fail('Chính sách đã thay đổi. Vui lòng lấy báo giá mới.','POLICY_CHANGED',409);if(q.totalAmount!==b.expectedTotalAmount)fail('Giá đã thay đổi. Vui lòng lấy báo giá mới.','PRICE_CHANGED',409);
 const rooms=freeRooms(s,b);if(!rooms.length)fail('Không còn phòng trong khoảng ngày này.','NO_AVAILABILITY',409);
 const recent=s.bookings.filter(x=>x.ip===ip&&Date.parse(x.createdAt)>Date.now()-3600000);if(recent.length>=5)throw new AppError(429,'RATE_LIMITED','Tối đa 5 yêu cầu đặt phòng trong một giờ.',3600);
 let bookingCode;do{bookingCode=crypto.randomBytes(4).toString('hex').toUpperCase();}while(s.bookings.some(x=>x.bookingCode===bookingCode));
 const booking={...b,...q,_id:id(),bookingCode,roomId:rooms[0]._id,status:'PENDING',createdAt:new Date().toISOString(),holdExpiresAt:new Date(Date.now()+86400000).toISOString(),depositAmount:0,ip,fingerprint,internalNotes:'',idNumber:''};s.bookings.push(booking);log(s,'Khách','CREATE_BOOKING',bookingCode);return bookingResult(booking);
}
function lookup(s,body,ip){expire(s);const now=Date.now();for(const [k,v] of Object.entries(s.lookupFailures))if(v.until<=now)delete s.lookupFailures[k];let f=s.lookupFailures[ip];if(f&&f.count>=10) return {error:new AppError(429,'RATE_LIMITED','Bạn đã tra cứu sai 10 lần. Vui lòng thử lại sau 15 phút.',Math.ceil((f.until-now)/1000))};const code=String(body.bookingCode||'').trim().toUpperCase(),email=String(body.email||'').trim().toLowerCase(),b=s.bookings.find(b=>b.bookingCode===code&&b.email===email);if(!b){if(!f)f=s.lookupFailures[ip]={count:0,until:now+900000};f.count++;return {error:new AppError(404,'NOT_FOUND','Không tìm thấy thông tin đặt phòng hợp lệ.')};}return {data:Object.fromEntries(['bookingCode','roomTypeName','checkIn','checkOut','numberOfNights','guestCount','totalAmount','depositAmount','status','holdExpiresAt'].map(k=>[k,b[k]]))};}
function transition(s,code,action,body,actor){expire(s);const b=s.bookings.find(b=>b.bookingCode===code);if(!b)fail('Không tìm thấy booking.','NOT_FOUND',404);const r=s.rooms.find(r=>r._id===b.roomId);
 if(action==='deposit'){const amount=Number(body.amount);if(!money(amount)||amount===0||!['PENDING','CONFIRMED','CHECKED_IN'].includes(b.status)||b.depositAmount+amount>b.totalAmount)fail('Số tiền cọc hoặc trạng thái không hợp lệ.');b.depositAmount+=amount;}
 else if(action==='confirm'){if(b.status!=='PENDING')fail('Chỉ xác nhận booking đang chờ.','STATE_CONFLICT',409);b.status='CONFIRMED';}
 else if(action==='checkin'){if(b.status!=='CONFIRMED'||b.checkIn>today()||b.checkOut<=today()||r.status!=='CLEAN_VACANT')fail('Cần booking xác nhận, đúng kỳ lưu trú và phòng sạch trống.','STATE_CONFLICT',409);if(!/^\d{9}(\d{3})?$/.test(String(body.idNumber||'')))fail('Nhập CCCD 12 số hoặc CMND 9 số.');b.idNumber=body.idNumber;b.internalNotes=String(body.internalNotes||'').slice(0,2000);b.status='CHECKED_IN';r.status='OCCUPIED';b.actualCheckIn=new Date().toISOString();}
 else if(action==='checkout'){if(b.status!=='CHECKED_IN')fail('Chỉ trả phòng cho khách đang ở.','STATE_CONFLICT',409);b.status='COMPLETED';b.actualCheckOut=new Date().toISOString();r.status='DIRTY_VACANT';}
 else if(action==='cancel'){if(!['PENDING','CONFIRMED'].includes(b.status))fail('Không thể huỷ booking ở trạng thái này.','STATE_CONFLICT',409);const hours=(Date.parse(`${b.checkIn}T${b.settingsSnapshot.checkInTime}:00+07:00`)-Date.now())/3600000;const rule=b.settingsSnapshot.cancellationRules.find(x=>hours>=x.hoursBefore);b.refundAmount=Math.floor(b.depositAmount*(rule?.refundPercent||0)/100);b.status='CANCELLED';}
 else fail('Thao tác không hợp lệ.');log(s,actor,action.toUpperCase(),code);return b;
}
function report(s,month){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))fail('Tháng phải có định dạng YYYY-MM.');expire(s);const bookings=s.bookings.filter(b=>b.checkIn.startsWith(month));const active=bookings.filter(b=>['CONFIRMED','CHECKED_IN','COMPLETED'].includes(b.status));return {month,bookingCount:bookings.length,confirmedCount:active.length,totalAmount:active.reduce((a,b)=>a+b.totalAmount,0),depositAmount:active.reduce((a,b)=>a+b.depositAmount,0),nights:active.reduce((a,b)=>a+b.numberOfNights,0),byStatus:Object.entries(statusLabels).map(([status,label])=>({status,label,count:bookings.filter(b=>b.status===status).length})),bookings};}
module.exports={AppError,fail,today,day,add,money,id,statusLabels,seedData,upgradeData,criteria,expire,quote,availability,createBooking,lookup,transition,report,log};
